# Generated by Django 3.2.5 on 2021-08-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LikeKPop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idol_name', models.CharField(max_length=100)),
                ('idol_group', models.TextField()),
                ('idol_image', models.TextField()),
            ],
        ),
    ]
